version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: shop-api
    ports:
      - "3333:3333" 
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis
    environment:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
  db:
    build: .docker/postgres
    container_name: shop-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shop-db

  
